name: CI

on:
  pull_request: {}
  push:
    branches:
      - master

concurrency:
  group: $-$
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust: ["1.31", stable]
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{matrix.rust}}
    - run: cargo build --all-targets
    - run: cargo test --all-targets
      if: matrix.rust == 'stable'
    - run: cargo test --doc
      if: matrix.rust == 'stable'

  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@1.75.0
      with:
        components: clippy
    - run: cargo clippy --all-features --all-targets -- -D warnings

  rustfmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt
    - run: cargo fmt --check --all
