name: build

on: [push]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  code-checking:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.31.0
          - stable
    concurrency: 
      group: ${{ github.ref }}-code-checking-${{ matrix.rust }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          components: rustfmt,clippy

      - uses: taiki-e/install-action@cargo-hack
          
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-code-checking-${{ hashFiles('**/Cargo.lock') }}

      - name: run lint
        run: cargo fmt --check

      - name: run check on features
        run: cargo hack check --feature-powerset

      - name: run clippy
        run: cargo clippy --all-targets --all-features --tests

  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.31.0
          - stable
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run tests
      run: cargo test

    - name: Run tests without default features
      run: cargo test --no-default-features
